# Generated by Django 5.2.17 on 2026-08-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='unidad',
            field=models.CharField(choices=[('UNIDAD', 'Unidad'), ('ML', 'Mililitro (ml)'), ('LT', 'Litro (lt)'), ('KG', 'Kilogramo (kg)'), ('G', 'Gramo (g)'), ('CAJA', 'Caja'), ('PACK', 'Pack'), ('SIXPACK', 'Six-pack')], default='UNIDAD', max_length=20),
        ),
    ]
