# Generated by Django 5.2.17 on 2026-08-20 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas_por_cobrar', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abono',
            name='tipo_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.tipopago'),
        ),
        migrations.AddField(
            model_name='deuda',
            name='venta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deuda', to='ventas.venta'),
        ),
        migrations.AddField(
            model_name='abono',
            name='deuda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='cuentas_por_cobrar.deuda'),
        ),
    ]
